### ISSUE TITLE
Level format structure

### ISSUE THREAD

**Issue by eexsty** [eexsty/zhixya#3]
# Level format structure

## Summary

This issue addresses how we should structure the level format and what type of file (JSON, TOML, RON, XML, ...) should we use, and why?

## The problem

The problem with many level format types is that they are not easy to read by humans and are very long.

## How we can solve that?

That's where the problem really comes from. We should use a suitable format for this kind of thing, firstly, I advise you to use TOML or RON, as they are quite readable and easy to understand.

### Level format sections

It is good to separate in several sections in the same file:
* **Level description:** Information about the grid, background color, the level format version, level identification, and other useful information.
* **Tilesets:** All tilesets used in the level. Each tile should be correspondent to the grid size.
* **Layers:** Each layer would be a collection of tilesets, whereas the layers on top of each other would be drawn in the order they are defined.

## Final considerations

Suggestions are appreciated for new sections, or if you have a better idea about how to structure the level format feel free to comment down below. Thank
you for the attention.

**Comment by eexsty** [comment]
## Properties system

As suggested by @Nightdavisao, we should add something like a property system to facilitate interactions with objects outside the editor. My proposed solution would be to add the possibility to create custom fields for each object on the map. For example:
```toml
[layer.layer_name]
defaults = {
    custom_fields = {
        physics_layer = "World"
    }
}

[[layer.layer_name.objects]]
custom_fields = {
    physics_layer = "Hello" # Inherit default fields and override them.   
}
```

## Alternative for tags in TOML

I think that for readability, it would be much better to use TOML. As an alternative to tags, we could use one more field in the following way:
```toml
[layer.layer_name]
defaults = {
    fill_type = "single",
}

[[layers.layer_name.objects]]
fill_type = "area"
texture = { tilemap = "grass", index = 4 }
pos1 = { x = 1, y = 1 }
pos2 = { x = 5, y = 5 }
```
